Gursaanj/dossier menu Functionality
m4rtint/GGJ2021 pull request #13
Opened 2021-01-29 22:25 UTC by Gursaanj

Created Dossier Menu canvas with temp placeholder on the labels and image. Created simple UI control script for functionality

2021-01-29 22:27 UTC, m4rtint commented on Assets/_GameJamCat/Scripts/UI/DossierMenu.cs
> +                transform.localScale = Vector3.one;
transform.localScale = _isMenuOpen ? Vector3.zero : Vector3.one

2021-01-29 22:34 UTC, Gursaanj commented on Assets/_GameJamCat/Scripts/UI/DossierMenu.cs
> +                transform.localScale = Vector3.one;
Good catch

2021-01-29 22:39 UTC, m4rtint commented
![1](https://user-images.githubusercontent.com/5779541/106334563-c86d4c80-623f-11eb-948b-dcca2cc62208.PNG)
Hey UI Text elements are kinda off, can you fix it?

2021-01-29 22:39 UTC, m4rtint requested changes
UI Changes needed

2021-01-29 23:40 UTC, Gursaanj commented
> ![1](https://user-images.githubusercontent.com/5779541/106334563-c86d4c80-623f-11eb-948b-dcca2cc62208.PNG)
> Hey UI Text elements are kinda off, can you fix it?

Oh woah not sure how that came about, yeah will fix in like 30 min

2021-01-30 02:03 UTC, m4rtint approved these changes

2021-01-30 02:05 UTC, merged